# Adding D unittests
#
#  Copyright (c) 2010 Jens Mueller <jens.k.mueller@gmx.de>
#
# All rights reserved.
#
# See LICENSE for details.
#

macro(target_add_unittests _target _sourceFiles)
    set(_testname "test_${_target}")
    set(main_unittest "${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/unittest.d")

    if(NOT EXISTS ${main_unittest})
        file(WRITE ${main_unittest} "// Generated by UseDUnittest.cmake\nint main() { return 0; }")
    endif()

    add_executable(test_${_target} ${_sourceFiles})
    add_dependencies(test_${_target} ${_target})
    target_compile_options(flow-core PRIVATE "-unittest")
    set_target_properties(test_${_target} PROPERTIES LINK_FLAGS "-main")
    
    get_target_property(include_dirs ${_target} INCLUDE_DIRECTORIES)
    foreach(include_dir ${include_dirs})
        if(include_dir)
            target_include_directories(test_${_target} PRIVATE "${include_dir}")
        endif()
    endforeach()

    get_target_property(libs ${_target} LINK_LIBRARIES)
    foreach(lib ${libs})
        if(lib)
            target_link_libraries(test_${_target} ${lib})
        endif()
    endforeach()

    add_test(NAME test_${_target}
        COMMAND "$<TARGET_FILE:test_${_target}>")
    set_tests_properties(test_${_target} PROPERTIES ENVIRONMENT "LD_LIBRARY_PATH=${CMAKE_CURRENT_SOURCE_DIR}/${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
endmacro()
